### ISSUE TITLE
Get data from two tables on list view

### ISSUE THREAD

**Issue by daniel2504** [shannah/xataface#108]
Hello together,

i got stucked on the point I want to get data from two tables in my default list view.

I have two tables:

1. adbwebsite

messageaddress | date | time | message

From this table I get the fields "messageaddress", "date", "time", "message" and some more. Its the main table.

2. addressrecords

Address | AddressDescription | Location

From this table I want to get the data from the field "AdressDescription" in the list view where Address matches messageaddress.

Address is for example 1234567* and messageaddress is 1234567 (The * is always added by software on the Address-Field in the addressrecords table. On the match comparision it should be ignorated)

There are some messages from messageaddresses where no AddressDescription is available yet.

My target is to get the following output in the default list view:

date | time | messageaddress | AddressDescription | message

In cases where AddressDescription is not available for, the data from adbebsite should be shown and the field AddressDescription should be left empty.

I would thank you soo much, if somone could help me with this. I tried for hours but failed always.

 BTW: Sorry for my english skills.

Regards,
Dan

**Comment by shannah** [comment]
This was answered in the mailing list.
