### ISSUE TITLE
selecting related record opens new record form in mobile

### ISSUE THREAD

**Issue by airdrummer** [shannah/xataface#119]
viewing  related records in mobile, select a record to view, new record form is presented.
<img width="570" alt="list of related records" src="https://user-images.githubusercontent.com/476083/110244043-e4dd6280-7f2a-11eb-978e-327a56fb985c.png">
<img width="570" alt="select r.record get new rec form" src="https://user-images.githubusercontent.com/476083/110244062-fcb4e680-7f2a-11eb-9e7e-6eda079e0000.png">

**Comment by shannah** [comment]
Fixed this yesterday.  If you update to the latest it should work now.

**Comment by airdrummer** [comment]
super! thanx...u r an earlybird;-)
