### ISSUE TITLE
table tabs unavailable in mobile view

### ISSUE THREAD

**Issue by airdrummer** [shannah/xataface#120]
only the 1st table is accessible
<img width="570" alt="no menu for othr tables" src="https://user-images.githubusercontent.com/476083/110244177-81a00000-7f2b-11eb-94ee-cec2a8e50e7b.png">
note lack of table selection

**Comment by shannah** [comment]
That's odd.  The tables should be rendered as tabs at the bottom of the screen.  Try updating to the latest and see if that fixes it.

**Comment by airdrummer** [comment]
nope, on my letartliveon.com site i get a green circle w/3line burger that does nothing:
`<div class="zoom" style="bottom: 24px;">
                                      <a class="zoom-fab zoom-btn-large" id="zoomBtn"><i class="material-icons">menu</i></a>
                     <ul class="zoom-menu">
                                                      <li><a class="zoom-fab zoom-btn-sm zoom-btn-person scale-transition scale-out zoom-btn-action-new" href="https://letartliveon.com/lalo_DB/index.php?-action=new&amp;-table=lalo_artists"><i class="material-icons">add</i></a></li>
                                                      <li><a class="zoom-fab zoom-btn-sm zoom-btn-person scale-transition scale-out zoom-btn-action-table_actions" href=""><i class="material-icons">more_vert</i></a></li>
                                              </ul>
                                 
               </div>`
whitespace sic...
on my cg db i get the green button w/ 3 vertical dots:
`<div class="zoom" style="bottom: 26px;">
                 
                                             
                         <a class="zoom-fab zoom-btn-large" id="zoomBtn" title="" href=""><i class="material-icons">more_vert</i></a>
                                                        
               </div>`

**Comment by shannah** [comment]
Check your javascript error log and PHP error log.

**Comment by airdrummer** [comment]
TypeError: ActionSheet is not a constructor

**Comment by airdrummer** [comment]
Block "before_table_tabs_mobile"
menu
Block "after_table_tabs_mobile"

**Comment by shannah** [comment]
I see.  All of my apps use the _tables action category for my table tabs, which overrides the _tables section of the conf.ini and is more flexible.  See (Customizing Navigation Menu)[https://shannah.github.io/xataface-manual/#tables-navigation-menu) for details on this procedure.

I have just [committed a fix](https://github.com/shannah/xataface/commit/75d4f60b3bc28c53310f04bbadc8f1fd4d0089fc) that will display the table tabs without having to do this.

**Comment by airdrummer** [comment]
thanx! php log obe then?

**Comment by airdrummer** [comment]
worx gr8, thanx!-) i can't keep up with all ur new features except when they break my apps;-}
