### ISSUE TITLE
Safe to empty dataface__record_mtimes?

### ISSUE THREAD

**Issue by mike-at-acs** [shannah/xataface#122]
Our dataface__record_mtimes table has grown to over 2.8 million lines on our site (in constant use).  
Is it safe to completely empty that table via phpmyadmin or will that cause functionality issues for our users?
Is the usage of that table documented somewhere? 
Thanks in advance.

**Comment by shannah** [comment]
This records modification times of individual records.  If you are using certain caching features, then it may use this table to determine if the cache should be invalidated.  It should be safe to delete this table, but I suggest not deleting it, as this information may be helpful to the app.

**Comment by mike-at-acs** [comment]
OK.  Will leave it as is for now.  Thanks for the quick turnaround!
