### ISSUE TITLE
actions.ini: Using $record in url makes new record creation fail

### ISSUE THREAD

**Issue by malaire** [shannah/xataface#47]
If I add following action to actions.ini:

    [MyActionButton]
    category = record_actions
    url = "MyActionURL?id={$record->val('TableID')}"

Then I can't create new records anymore. When I go to create new record and save it, I get 500 Internal Server Error with empty page and no error message. This is somehow related to the use of $record in that action, even through that action is not even visible on the "Record successfully saved" page which fails.

As a workaround for this bug, adding following condition seems to make this work:

    condition = "isset($record)"

**Comment by shannah** [comment]
Add
url_condition="$record"

If $record is null, then it will crash when Xataface tries to get the URL
of your action.  Adding url_condition tells xataface to check that
condition before trying to get the URL of the action.

Alternatively or additionally you could provide:
condition="$record"

which will skip the action entirely if $record is null.

Steve

On Thu, Jan 29, 2015 at 12:10 AM, malaire <notifications@github.com> wrote:

> If I add following action to actions.ini:
>
> [MyActionButton]
> category = record_actions
> url = "MyActionURL?id={$record->val('TableID')}"
>
> Then I can't create new records anymore. When I go to create new record
> and save it, I get 500 Internal Server Error with empty page and no error
> message. This is somehow related to the use of $record in that action, even
> through that action is not even visible on the "Record successfully saved"
> page which fails.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shannah/xataface/issues/47>.
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by malaire** [comment]
Why $record is null on "Record successfully saved" page?

**Comment by shannah** [comment]
$record (in the context of actions.ini) refers to the current record in the
result set.  This can be null for a variety of reasons, including doing a
search that returns an empty result set.  Any time you are calling methods
on $record inside an action directive, you need to guard it with a
condition check to make sure that record is not null.

Steve

On Thu, Jan 29, 2015 at 8:26 AM, malaire <notifications@github.com> wrote:

> Why $record is null on "Record successfully saved" page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shannah/xataface/issues/47#issuecomment-72054778>.
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by malaire** [comment]
ok, I guess xataface could still die a bit more gracefully here, internal server error with no error message anywhere is quite hard to debug.
