### ISSUE TITLE
"zero" key foreign key trouble in N-N relationship 

### ISSUE THREAD

**Issue by philgris** [shannah/xataface#54]
In the case of N-N relationship there is some trouble when we have some record using list-record with 0 value which are not recorded in the database.
for example : you have the case [tab1] - [tab12] - [tab2] and the ralationnal table [tab12] have some foreign key fk_tab3 with [tab3] define like {id(INT), label(TXT), ...} .
the problem comes when we want to add a new related record with the 'add new tab2 records' tab , and  when we select in a list of the [tab3] a record with a 0 primary key.
the problem is the same if we have a foreign key fk_tab2 with [tab2] define like {id(INT), label(TXT), ...}  with a id=0.
The only way to process is to reopen the relational (tab12) and the related (tab2) records and select the value in the selected list (tab3, ...)

**Comment by shannah** [comment]
Check $colVals here to see that the columns are propagated properly:
https://github.com/shannah/xataface/blob/master/Dataface/ExistingRelatedRecordForm.php#L390

The actual code that adds the existing related record is here:

https://github.com/shannah/xataface/blob/master/Dataface/IO.php#L1549
Follow this through and see where the "zero" gives a problem.
