### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by viharm** [shannah/xataface#57]
Steve,

Not sure if this is the primary discussion/issue platform or Google Groups.

Ref. Google Groups topic https://groups.google.com/forum/#!topic/xataface/Vsx8Svc0Zak, sorry for the delay in completing this, however I have finally finished work on version 02.00.00; which support some additional features. See (https://bitbucket.org/viharm/xatafaceldapauth/). I am very new to licensing, so split the directory authentication and database authentication into two separate projects and use them as dependencies. The main ldap.php is modified to suit and released under Apache v2. If you feel this is inappropriate or incompatible please advise.

Best regards,
ViHAR

**Comment by shannah** [comment]
This is great!  Thanks for posting this.

**Comment by viharm** [comment]
I have been reading up on the licensing approach, and it appears that if
the original code (your vanilla LDAP module) is released under GPL then the
derivitaive must also be released under GPL.

Please clarify/confirm. If this is the case then is it possible for you to
re-release under a more permissive licence? If not I will re-release under
GPL2.

I want to do it right this time, so I am not jumping around licences :-P


​Regards.​

**Comment by shannah** [comment]
Technically that is true.  I use GPL for Xataface because it incorporates
some libraries and CSS that may be GPL.  For the modules I plan to move
them to a more permissive license like Apache or MIT as most don't have any
GPL dependencies.  I just haven't gotten around to it yet.

On Mon, Jun 8, 2015 at 11:54 PM, viharm <notifications@github.com> wrote:

> I have been reading up on the licensing approach, and it appears that if
> the original code (your vanilla LDAP module) is released under GPL then the
> derivitaive must also be released under GPL.
>
> Please clarify/confirm. If this is the case then is it possible for you to
> re-release under a more permissive licence? If not I will re-release under
> GPL2.
>
> I want to do it right this time, so I am not jumping around licences :-P
>
>
> ​Regards.​
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shannah/xataface/issues/57#issuecomment-110252819>.
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by viharm** [comment]
Hi Steve,

Thanks for your response, and the explanation. For now, I have released the module under GPLv2, so it can be integrated straightaway. It uses discrete libraries which are separately released under BSD/Apache licenses, but the module itself is GPLv2.

One of the other posters on the Google Groups threads has helped with the testing, so several major issues were resolved and it is now working with the additional features I had envisioned. Some minor issues remain and are documented at https://bitbucket.org/viharm/xatafaceldapauth/issues

I could not find any specific guidelines on variables usage in the module developer documentation; so have used *Kint* for debugging using some a global variable for debugging.  If you need any further help in integrating, please advise.
