### ISSUE TITLE
PHP7 dropped mysql-extension

### ISSUE THREAD

**Issue by NeroBurner** [shannah/xataface#71]
PHP7 dropped the mysql-extension [1]

Hence the latest release of Xataface (2.1.2) won't work on PHP7

[1] http://php.net/manual/en/migration70.removed-exts-sapis.php

**Comment by manifold23** [comment]
On 1/15/2016 4:42 AM, NeroBurner wrote:
> PHP7 dropped the mysql-extension [1]
> 
> Hence the latest release of Xataface (2.1.2) won't work on PHP7
> 
> [1] http://php.net/manual/en/migration70.removed-exts-sapis.php
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/shannah/xataface/issues/71
> 
Hello,

It seems that there may be a semi-solution to this, which you can see here:
https://ckon.wordpress.com/2015/08/06/put-mysql-functions-back-into-php-7/

While not ideal, and perhaps not a permanent solution, this may offer
some xataface users an option if they must move to php7.

Also, this may be a possible solution:
http://sourceforge.net/projects/mysqlwithmysqli/

As always, thank you for xataface!

-rckeller

**Comment by shannah** [comment]
Or use mysqli with xataface
http://xataface-tips.blogspot.ca/2014/06/using-mysqli-in-xataface.html?m=1

Best regards
Steve


On Friday, 15 January 2016, manifold23 <notifications@github.com> wrote:

> On 1/15/2016 4:42 AM, NeroBurner wrote:
> > PHP7 dropped the mysql-extension [1]
> >
> > Hence the latest release of Xataface (2.1.2) won't work on PHP7
> >
> > [1] http://php.net/manual/en/migration70.removed-exts-sapis.php
> >
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/shannah/xataface/issues/71
> >
> Hello,
>
> It seems that there may be a semi-solution to this, which you can see here:
> https://ckon.wordpress.com/2015/08/06/put-mysql-functions-back-into-php-7/
>
> While not ideal, and perhaps not a permanent solution, this may offer
> some xataface users an option if they must move to php7.
>
> Also, this may be a possible solution:
> http://sourceforge.net/projects/mysqlwithmysqli/
>
> As always, thank you for xataface!
>
> -rckeller
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shannah/xataface/issues/71#issuecomment-171936409>.
>


-- 
Steve Hannah
Web Lite Solutions Corp.
