### ISSUE TITLE
release recent xataface work?

### ISSUE THREAD

**Issue by dckc** [shannah/xataface#96]
Using Xataface v2.1.3 released Aug 31, 2016 with PHP 7.0.25-0ubuntu0.16.04.1, I'm running into the `T_ENCAPSED_AND_WHITESPACE` problem fixed Sep 16, 2016 in a3926792 .

I would very much appreciate a release that included recent work such as this.

**Comment by dgleba** [comment]
You don't need a release.  Just download a zip of this repo and use it.

**Comment by dgleba** [comment]
I can't say that I have.
